baseURL = "https://blog.clayliu.com/"
languageCode = "zh"
title = "Clay's Blog"
theme = "Niello"

staticDir = ["static", "themes/Niello/static"]

[params]
keywords = ""
description = ""
copyright = "&#xA9; 2021 by clayliu. All Rights Reserved."
google_ad_client = "ca-pub-******"
ga = "UA-******"
sharethis = ""

[menu]
    [[menu.niello]]
    name = "Home"
    url = "/"
    weight = 1

    [[menu.niello]]
    name = "Contact"
    url = "/post/contact/"
    weight = 2
    
[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = 'monokai'
    tabWidth = 4



[module]
  [module.hugoVersion]
    extended = true
    min = '0.87.0'
